app:
  name: "api-api-fast"
  userId: "8a0a0be3-bbdf-4762-bf26-4a23b2"
  projectName: "api-api-fast"
  namespace: "ns-tarakit-istad-gmail-com-065e6567"
  framework: "fastapi"
  containerPort: 8000
  servicePort: 80
  domain: "autonomous-istad.com"
  host: "api-api-fast-ns-tarakit-istad-gmail-com-065e6567.autonomous-istad.com" # managed-by-jenkins-host

image:
  repository: "goharbor-itp.anajak-khmer.site/deployment-pipeline/8a0a0be3-bbdf-4762-bf26-4a23b2/api-api-fast"
  tag: "api-api-fast-3961e242" # managed-by-jenkins-image-tag
  pullPolicy: "IfNotPresent"

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    enabled: true
    secretName: "api-api-fast-tls"

imagePullSecrets:
  - name: "registry-secret"

envJson: |
  []

vault:
  enabled: false
  secretStoreName: "vault-backend"
  secretStoreKind: "ClusterSecretStore"
  envPath: ""

probes:
  mode: "tcp"
  startup:
    enabled: false
    path: "/"
    initialDelaySeconds: 0
    periodSeconds: 5
    failureThreshold: 24
  readiness:
    enabled: true
    path: "/"
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    enabled: true
    path: "/"
    initialDelaySeconds: 30
    periodSeconds: 15
    failureThreshold: 3
