app:
  name: "reactjs-devop10-template"
  userId: "93e629b5-bce5-44f2-a6ca-7606ab"
  projectName: "reactjs-devop10-template"
  namespace: "ns-lyvanna544-gmail-com-242e59dc"
  framework: "react"
  containerPort: 80
  servicePort: 80
  domain: "autonomous-istad.com"
  host: "reactjs-devop10-template-ns-lyvanna544-gmail-com-242e59dc.autonomous-istad.com" # managed-by-jenkins-host

image:
  repository: "harbor.devith.it.com/deployment-pipeline/93e629b5-bce5-44f2-a6ca-7606ab/reactjs-devop10-template"
  tag: "93e629b5-bce5-44f2-a6ca-7606ab-79-51bafe790b20" # managed-by-jenkins-image-tag
  pullPolicy: "IfNotPresent"

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    enabled: true
    secretName: "reactjs-devop10-template-tls"

imagePullSecrets:
  - name: "registry-secret"

envJson: |
  []

probes:
  mode: "http"
  startup:
    enabled: false
    path: "/"
    initialDelaySeconds: 0
    periodSeconds: 5
    failureThreshold: 24
  readiness:
    enabled: true
    path: "/"
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    enabled: true
    path: "/"
    initialDelaySeconds: 30
    periodSeconds: 15
    failureThreshold: 3
