app:
  name: "html-website"
  userId: "9c3e9f10-b661-4510-b48c-a1e315"
  projectName: "html-website"
  namespace: "ns-kaisenzzza-gmail-com-1b0971c4"
  framework: "static"
  containerPort: 80
  servicePort: 80
  domain: "autonomous-istad.com"
  host: "html-website-ns-kaisenzzza-gmail-com-1b0971c4.autonomous-istad.com" # managed-by-jenkins-host

image:
  repository: "goharbor-itp.anajak-khmer.site/deployment-pipeline/9c3e9f10-b661-4510-b48c-a1e315/html-website"
  tag: "html-website-e4df9a07" # managed-by-jenkins-image-tag
  pullPolicy: "IfNotPresent"

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    enabled: true
    secretName: "html-website-tls"

imagePullSecrets:
  - name: "registry-secret"

envJson: |
  []

vault:
  enabled: false
  secretStoreName: "vault-backend"
  secretStoreKind: "ClusterSecretStore"
  envPath: ""

probes:
  mode: "http"
  startup:
    enabled: false
    path: "/"
    initialDelaySeconds: 0
    periodSeconds: 5
    failureThreshold: 24
  readiness:
    enabled: true
    path: "/"
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    enabled: true
    path: "/"
    initialDelaySeconds: 30
    periodSeconds: 15
    failureThreshold: 3
