app:
  name: "reactjs-devops-demo"
  userId: "64780181-e021-45be-9fe0-9dda0c"
  projectName: "reactjs-devops-demo"
  namespace: "ns-porkeat-c18c6214"
  framework: "react"
  containerPort: 80
  servicePort: 80
  domain: "autonomous-istad.com"
  host: "reactjs-devops-demo-ns-porkeat-c18c6214.autonomous-istad.com" # managed-by-jenkins-host

image:
  repository: "gohabor.anajak-khmer.site/deployment-pipeline/64780181-e021-45be-9fe0-9dda0c/reactjs-devops-demo"
  tag: "reactjs-devops-demo-bbbfe57e" # managed-by-jenkins-image-tag
  pullPolicy: "IfNotPresent"

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    enabled: true
    secretName: "reactjs-devops-demo-tls"

imagePullSecrets:
  - name: "registry-secret"

envJson: |
  []

probes:
  mode: "http"
  startup:
    enabled: false
    path: "/"
    initialDelaySeconds: 0
    periodSeconds: 5
    failureThreshold: 24
  readiness:
    enabled: true
    path: "/"
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    enabled: true
    path: "/"
    initialDelaySeconds: 30
    periodSeconds: 15
    failureThreshold: 3
