app:
  name: "lumina-react"
  userId: "2dd31e5d-76e5-41d1-9399-004979"
  projectName: "lumina-react"
  namespace: "ns-a8s-admin-c95e01ae"
  framework: "react"
  containerPort: 80
  servicePort: 80
  domain: "autonomous-istad.com"
  host: "lumina-react-ns-a8s-admin-c95e01ae.autonomous-istad.com" # managed-by-jenkins-host

image:
  repository: "goharbor-itp.anajak-khmer.site/deployment-pipeline/2dd31e5d-76e5-41d1-9399-004979/lumina-react"
  tag: "lumina-react-2f53d330" # managed-by-jenkins-image-tag
  pullPolicy: "IfNotPresent"

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    enabled: true
    secretName: "lumina-react-tls"

imagePullSecrets:
  - name: "registry-secret"

envJson: |
  []

vault:
  enabled: false
  secretStoreName: "vault-backend"
  secretStoreKind: "ClusterSecretStore"
  envPath: ""

probes:
  mode: "http"
  startup:
    enabled: false
    path: "/"
    initialDelaySeconds: 0
    periodSeconds: 5
    failureThreshold: 24
  readiness:
    enabled: true
    path: "/"
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    enabled: true
    path: "/"
    initialDelaySeconds: 30
    periodSeconds: 15
    failureThreshold: 3
