app:
  name: "reactjs-fullstack1st-template"
  userId: "c275465f-2398-4499-b5d5-cd93e7"
  projectName: "reactjs-fullstack1st-template"
  namespace: "ns-a8s-admin-c36fc7af"
  framework: "react"
  containerPort: 80
  servicePort: 80
  domain: "autonomous-istad.com"
  host: "reactjs-fullstack1st-template-ns-a8s-admin-c36fc7af.autonomous-istad.com" # managed-by-jenkins-host

image:
  repository: "gohabor.anajak-khmer.site/deployment-pipeline/c275465f-2398-4499-b5d5-cd93e7/reactjs-fullstack1st-template"
  tag: "reactjs-fullstack1st-template-5412ffac" # managed-by-jenkins-image-tag
  pullPolicy: "IfNotPresent"

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    enabled: true
    secretName: "reactjs-fullstack1st-template-tls"

imagePullSecrets:
  - name: "registry-secret"

envJson: |
  []

probes:
  mode: "http"
  startup:
    enabled: false
    path: "/"
    initialDelaySeconds: 0
    periodSeconds: 5
    failureThreshold: 24
  readiness:
    enabled: true
    path: "/"
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    enabled: true
    path: "/"
    initialDelaySeconds: 30
    periodSeconds: 15
    failureThreshold: 3
