app:
  name: "reactjs-devop8-template"
  userId: "52214a42-a768-4694-9e15-7e9cdb"
  projectName: "reactjs-devop8-template"
  namespace: "ns-pengseangsim210-gmail-com-9d7d574c"
  framework: "react"
  containerPort: 80
  servicePort: 80
  domain: "autonomous-istad.com"
  host: "reactjs-devop8-template-ns-pengseangsim210-gmail-com-9d7d574c.autonomous-istad.com" # managed-by-jenkins-host

image:
  repository: "goharbor-itp.anajak-khmer.site/deployment-pipeline/52214a42-a768-4694-9e15-7e9cdb/reactjs-devop8-template"
  tag: "reactjs-devop8-template-2e546ee4" # managed-by-jenkins-image-tag
  pullPolicy: "IfNotPresent"

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    enabled: true
    secretName: "reactjs-devop8-template-tls"

imagePullSecrets:
  - name: "registry-secret"

envJson: |
  []

vault:
  enabled: false
  secretStoreName: "vault-backend"
  secretStoreKind: "ClusterSecretStore"
  envPath: ""

probes:
  mode: "http"
  startup:
    enabled: false
    path: "/"
    initialDelaySeconds: 0
    periodSeconds: 5
    failureThreshold: 24
  readiness:
    enabled: true
    path: "/"
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    enabled: true
    path: "/"
    initialDelaySeconds: 30
    periodSeconds: 15
    failureThreshold: 3
