app:
  name: "spring-dpl"
  userId: "ab4e459b-2817-42c4-a3af-117ddc"
  projectName: "spring-dpl"
  namespace: "ns-tochratana-963a758e"
  framework: "springboot-gradle"
  containerPort: 8080
  servicePort: 80
  domain: "autonomous-istad.com"
  host: "spring-dpl-ns-tochratana-963a758e.autonomous-istad.com" # managed-by-jenkins-host

image:
  repository: "harbor.devith.it.com/deployment-pipeline/ab4e459b-2817-42c4-a3af-117ddc/spring-dpl"
  tag: "ab4e459b-2817-42c4-a3af-117ddc-61-0f72e7020610" # managed-by-jenkins-image-tag
  pullPolicy: "IfNotPresent"

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    enabled: true
    secretName: "spring-dpl-tls"

imagePullSecrets:
  - name: "registry-secret"

envJson: |
  []

probes:
  mode: "tcp"
  startup:
    enabled: true
    path: "/"
    initialDelaySeconds: 0
    periodSeconds: 5
    failureThreshold: 24
  readiness:
    enabled: true
    path: "/"
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    enabled: true
    path: "/"
    initialDelaySeconds: 30
    periodSeconds: 15
    failureThreshold: 3
