app:
  name: "reactjs"
  userId: "122d1924-4c05-41d4-878d-57293d"
  projectName: "reactjs"
  namespace: "ns-sorn-sophamarinet-c2332eff"
  framework: "react"
  containerPort: 80
  servicePort: 80
  domain: "autonomous-istad.com"
  host: "reactjs-ns-sorn-sophamarinet-c2332eff.autonomous-istad.com" # managed-by-jenkins-host

image:
  repository: "harbor.devith.it.com/deployment-pipeline/122d1924-4c05-41d4-878d-57293d/reactjs"
  tag: "122d1924-4c05-41d4-878d-57293d-64-c9d3359cc89c" # managed-by-jenkins-image-tag
  pullPolicy: "IfNotPresent"

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    enabled: true
    secretName: "reactjs-tls"

imagePullSecrets:
  - name: "registry-secret"

envJson: |
  []

probes:
  mode: "http"
  startup:
    enabled: false
    path: "/"
    initialDelaySeconds: 0
    periodSeconds: 5
    failureThreshold: 24
  readiness:
    enabled: true
    path: "/"
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    enabled: true
    path: "/"
    initialDelaySeconds: 30
    periodSeconds: 15
    failureThreshold: 3
